Consider all companions from all PRs descriptions
paritytech/pipeline-scripts pull request #19
Opened 2021-12-14 15:36 UTC by joao-paulo-parity

:exclamation: I have not tried this out yet. This PR is up for early review for those interested.

Notably this also does not merge master onto the PRs as discussed in https://github.com/paritytech/pipeline-scripts/issues/17. I still need to evaluate and document why it is necessary to do that.

closes #3

2021-12-15 16:16 UTC, joao-paulo-parity commented on check_dependent_project.sh
> +    --target "$org_github_prefix/$comp" \
since we'll be using `--target` from now on instead of the fixed `--substrate`, `--polkadot`, `--cumulus`, etc., `$this_repo_diener_arg` can be deprecated. I plan to do so in a future PR (https://github.com/paritytech/pipeline-scripts/issues/20).

2021-12-15 16:43 UTC, joao-paulo-parity commented on check_dependent_project.sh
> -
See the description or more specifically https://github.com/paritytech/pipeline-scripts/issues/17#issuecomment-994743929

2021-12-15 16:43 UTC, joao-paulo-parity commented on check_dependent_project.sh
> -  git merge master --verbose --no-edit -m "master was merged into the pr by check_dependent_project.sh main()"
See the description or more specifically https://github.com/paritytech/pipeline-scripts/issues/17#issuecomment-994743929

2021-12-15 16:45 UTC, joao-paulo-parity commented on check_dependent_project.sh
> -  echo "running checks for the default branch of $dependent_repo"
This is just duplicated logic which was moved into `patch_and_check_dependent`

2021-12-15 16:47 UTC, joao-paulo-parity commented
https://github.com/paritytech/substrate/pull/10496#issuecomment-994949254

The implementation scope for this PR is complete

2021-12-15 19:24 UTC, TriplEight requested changes
just a couple of nits. Otherwise, it should be tested.

2021-12-15 19:24 UTC, TriplEight commented on check_dependent_project.sh
> +  eval "${COMPANION_CHECK_COMMAND:-cargo check --all-targets --workspace}"
```suggestion
  eval "${COMPANION_CHECK_COMMAND:-'cargo check --all-targets --workspace'}"
```

2021-12-15 19:24 UTC, TriplEight commented on check_dependent_project.sh
> +  eval "${COMPANION_CHECK_COMMAND:-cargo check --all-targets --workspace}"
not quite sure if `eval` would eat it with spaces everywhere

2021-12-15 19:24 UTC, TriplEight commented on check_dependent_project.sh
> +    git clone --depth=1 "https://github.com/$org/$dependent_repo.git" "$dependent_repo_dir"
see the previous fix: https://github.com/paritytech/pipeline-scripts/pull/19/files#diff-df602127cd49392d5fb1da82c27351842395a47e788e0c6a77cf52d690ed1d2aL210

Sometimes it's too shallow, better update 1 to something 100 or ask github API about the PR source commit.

2021-12-16 07:28 UTC, joao-paulo-parity commented on check_dependent_project.sh
> +    git clone --depth=1 "https://github.com/$org/$dependent_repo.git" "$dependent_repo_dir"
This is not necessary anymore because the master merge is no longer done

2021-12-16 07:29 UTC, joao-paulo-parity commented on check_dependent_project.sh
> +  eval "${COMPANION_CHECK_COMMAND:-cargo check --all-targets --workspace}"
Eval executes the whole expression with spaces included. The current code works as intended.

2021-12-16 07:30 UTC, joao-paulo-parity commented
> just a couple of nits. Otherwise, it should be tested.

@TriplEight it was tested

https://github.com/paritytech/substrate/pull/10496#issue-1081143072
https://github.com/paritytech/substrate/pull/10496#issuecomment-994949254

2021-12-17 13:19 UTC, joao-paulo-parity commented
Moving to draft while I trial https://github.com/paritytech/pipeline-scripts/pull/19/commits/dae59336efa9773d0277cea0f8018a5e656e5cad

2021-12-17 14:06 UTC, TriplEight approved these changes

2021-12-17 14:06 UTC, TriplEight commented on check_dependent_project.sh
> +Both cases can be solved by merging master into $repo#$pr_number.
:heart:

2021-12-17 14:23 UTC, merged