add bench-bot infra docs
paritytech/pipeline-scripts pull request #58
Opened 2022-07-01 10:41 UTC by radupopa2010

2022-07-01 10:47 UTC, sergejparity commented on README.md
> +The machine needs to configred as a production gitlab-runer.
```suggestion
The machine needs to be configured as a production gitlab-runer.
```

2022-07-01 10:48 UTC, sergejparity commented on README.md
> +  * HOME for `gitlab-runner` needs to  be in `/home` because this is monunted on a disk witk more space then the root partition
```suggestion
  * HOME for `gitlab-runner` needs to  be in `/home` because this is mounted on a disk with more space then the root partition
```

2022-07-01 10:50 UTC, sergejparity commented on README.md
> +a test VM and add it to inventory everywhere `bm3` is mentiond.
```suggestion
a test VM and add it to inventory everywhere `bm3` is mentioned.
```

2022-07-01 10:51 UTC, sergejparity commented on README.md
> +          ### required for rustup ransible role
```suggestion
          ### required for rustup ansible role
```

2022-07-01 10:51 UTC, joao-paulo-parity requested changes

2022-07-01 10:51 UTC, joao-paulo-parity commented on README.md
> +  E. G. `/cmd queue -c bench-bot $ pallet dev pallet_balances`
Usage is already explained elsewhere. Also the mention of Substrate alone is not enough since the bot is also enabled for Polkadot and it'll be implemented for Cumulus in the future (#45).

```suggestion
The script through which command-bot runs benchmarks. See https://github.com/paritytech/command-bot#pull-request-command-queue for its usage.
```

2022-07-01 10:51 UTC, joao-paulo-parity commented on README.md
> +This bot runs on [bm3 machine](https://gitlab.parity.io/parity/devops/-/blob/master/inventory.yaml#L485),
Prefer a permanent link since changes in that file will make the line count change, then the reference will become misplaced

```suggestion
This bot runs on [bm3 machine](https://gitlab.parity.io/parity/devops/-/blob/462e85a44e9c84064a7f91d1402e499e27e07991/inventory.yaml#L485),
```

2022-07-01 10:51 UTC, joao-paulo-parity commented on README.md
> +  * HOME for `gitlab-runner` needs to  be in `/home` because this is monunted on a disk witk more space then the root partition
Some typos

```suggestion
  * `$HOME` for `gitlab-runner` needs to be within `/home` because it is mounted on a disk with more space than the root partition
```

2022-07-01 10:51 UTC, joao-paulo-parity commented on README.md
> +and there will be a lot of rust code compiled
```suggestion
and Rust's release artifacts require a lot of disk space
```

2022-07-01 10:51 UTC, joao-paulo-parity commented on README.md
> +  * install toolchain nightly
I think it's better to provide the actual commands here

2022-07-01 10:51 UTC, joao-paulo-parity commented on README.md
> +  * add wasm target
I think it's better to provide the actual commands here

2022-07-01 10:51 UTC, joao-paulo-parity commented on README.md
> +**When creating the VM helps a lot if you include your ssh public key**
```suggestion
**When creating the VM it's recommended to add your ssh public key**
```

Also add the reason why it's recommended

2022-07-01 10:51 UTC, joao-paulo-parity commented on README.md
> +In order not to disrupt the service, JP created a test command that uses gitlab tag `test-bench-bot`
Thanks for mentioning me, but it's not necessary

```suggestion
To avoid disrupting the production service while testing, a `test-bench-bot` configuration can be used, which uses the `test-bench-bot` tag instead of `bench-bot`. It can be tested as:
```

2022-07-01 10:53 UTC, sergejparity commented on README.md
> +/home/radu/.ssh/id_rsa_yubikey.pub
```suggestion
/home/$USER/.ssh/id_rsa_yubikey.pub
```

2022-07-01 10:54 UTC, sergejparity commented on README.md
> +3. Wait a bit and check for a commnet from the bot with the job that started
```suggestion
3. Wait a bit and check for a comment from the bot with the job that started
```

2022-07-01 10:55 UTC, sergejparity requested changes
Please fix some spelling

2022-07-01 11:09 UTC, radupopa2010 commented on README.md
> +  * install toolchain nightly
I will include a link to ansible code once it's reviewed and merged

2022-07-01 11:09 UTC, radupopa2010 commented on README.md
> +  * add wasm target
I will include a link to ansible code once it's reviewed and merged

2022-07-01 11:44 UTC, sergejparity approved these changes

2022-07-01 11:46 UTC, merged

2022-07-04 08:27 UTC, TriplEight commented
@radupopa2010 why did you resolve everything without applying the important and valid suggestions?

2022-07-04 10:51 UTC, TriplEight commented
it must've been because of github's issues last week