Prevent Rust feature bleed
paritytech/pipeline-scripts pull request #81
Opened 2022-10-06 18:25 UTC by ggwpez

See https://github.com/paritytech/substrate/pull/12341 for a description of the new script.

2022-10-06 20:57 UTC, mordamax approved these changes

2022-10-07 07:13 UTC, bkchr commented on rust-features.sh
> +#!/bin/bash
```suggestion
#!//usr/bin/env bash
```

There is no convention that `/bin/bash` exists.

2022-10-07 07:14 UTC, bkchr commented
@mordamax you are fine with maintaining this? My eyes bleed again a little bit after seeing this bash script.

2022-10-07 07:23 UTC, bkchr commented
BTW, there also exist this pr: https://github.com/paritytech/diener/pull/19

2022-10-07 10:53 UTC, mordamax commented
> @mordamax you are fine with maintaining this? My eyes bleed again a little bit after seeing this bash script.

I guess it's @paritytech-ci who maintain it in this case.
This repo is mainly for reusable CI scripts, to avoid dupe

but my opinion is that it's okay as long as it's relevantly simple, <=~100 lines

the existing stuff like check-dependent should be killed 100%
tryruntime and bench most probably will be moved & rewritten to command bot

2022-10-07 11:42 UTC, ggwpez commented
> BTW, there also exist this pr: [paritytech/diener#19](https://github.com/paritytech/diener/pull/19)

Interesting... I dont think parsing `Cargo.toml` files works for external dependencies from `crates.io`, or? (In case we ever release Substrate there :rofl:) But in any case, that check is additive to this one.

I am not happy with this as long-term solution, but for now it should prevent obvious blunders which can take a while to find otherwise. Recently I saw https://github.com/guppy-rs/guppy which is used by Diem and think could be a fit.

2022-10-07 11:46 UTC, bkchr commented
> I dont think parsing `Cargo.toml` files works for external dependencies from `crates.io`, or

You download the deps to the local cargo registry. So, this should work.



> Recently I saw https://github.com/guppy-rs/guppy which is used by Diem and think could be a fit.

I think I read about this somewhere before, but if that could be a fit, it would be nice.

2022-10-07 11:49 UTC, ggwpez commented
Okay then lets use this to get rid of some obvious errors and then make a long-term strategy?  
Like set out a scope of rules that we want to be checked and search for existing tools if they can do it or self implement.

2022-10-07 12:23 UTC, mutantcornholio commented on rust-features.sh
> +#!//usr/bin/env bash
Is this double leading accidental?

2022-10-07 12:24 UTC, ggwpez commented on rust-features.sh
> +#!//usr/bin/env bash
```suggestion
#!/usr/bin/env bash
```
Nope but it would still work :smile:

2022-10-07 12:24 UTC, ggwpez commented on rust-features.sh
> +#!//usr/bin/env bash
fixed

2022-10-07 12:28 UTC, mutantcornholio commented on rust-features.sh
> +done
This feels too complicated to be something that processes static data. Maybe we could organise data differently?  
The `"default,std never implies feature try-runtime"` syntax also seems hacky.

2022-10-07 12:33 UTC, mutantcornholio commented on rust-features.sh
> +		RET=0
I genuinely can't understand what's going on here...  
We have a variable that stores return code of `cargo tree`, and then we're nullifying it in the loop... But how is it used afterwards?

2022-10-07 12:37 UTC, mutantcornholio commented on rust-features.sh
> +	fi
Can't it be simplified like this?

```suggestion
	# Check if the forbidden feature is enabled anywhere in the workspace.
	if cargo tree --no-default-features --locked --workspace -e features --features "$ENABLED" | grep -q "feature \"$STAYS_DISABLED\""; then
		echo "✅ $ENABLED does not imply $STAYS_DISABLED in the workspace"
		return
	else
		echo "❌ $ENABLED implies $STAYS_DISABLED in the workspace"
	fi
```

Also, `-F` is probably implied here in `grep` invocation.

2022-10-07 12:39 UTC, mutantcornholio commented on rust-features.sh
> +command -v egrep >/dev/null 2>&1 || { echo >&2 "egrep is required but not installed. Aborting."; exit 1; }
is `egrep` used here somewhere?

2022-10-07 12:43 UTC, mutantcornholio requested changes

2022-10-07 12:43 UTC, mutantcornholio commented on rust-features.sh
> +	"default,std never implies feature try-runtime"
After spending time on reviewing this, I'd say this format ought to be changed.  
It's not self-descriptive, the fact that it expects "feature<space><feature_name>" at the end doesn't feel natural, and a lot of the code here is dedicated specifically to parsing of the format.

2022-10-07 12:44 UTC, ggwpez commented on rust-features.sh
> +done
Yea I can put it in some arrays instead. But then it needs more docs on how to use it. Like this it reads as natural sentence.

2022-10-07 12:48 UTC, ggwpez commented on rust-features.sh
> +	"default,std never implies feature try-runtime"
Okay I will simplify it.

2022-10-07 12:49 UTC, mutantcornholio commented on rust-features.sh
> +done
I believe that one comment line describing the format, would save a lot more time to the reader of the script than this idea of natural sentence, which actually not natural at all, but a strict format instead.

2022-10-12 11:16 UTC, ggwpez commented on rust-features.sh
> +done
I removed the data structure and parsing, should be much easier now :see_no_evil:

2022-10-12 11:19 UTC, ggwpez commented on rust-features.sh
> +command -v egrep >/dev/null 2>&1 || { echo >&2 "egrep is required but not installed. Aborting."; exit 1; }
not anymore

2022-10-12 11:51 UTC, mutantcornholio commented on rust-features.sh
> +		elif echo "$OUTPUT" | grep -qF "feature \"$STAYS_DISABLED\""; then
I see three different approaches to checking return code here.  
This one, inside `if`, then `RET=0; command || RET=$?`, and `IS_NOT_SUPPORTED=$(command || echo $?)`.  
Maybe put all of them into `if`'s?

2022-10-12 11:53 UTC, ggwpez commented on rust-features.sh
> +		elif echo "$OUTPUT" | grep -qF "feature \"$STAYS_DISABLED\""; then
I kind of wanted to keep the lines short, but I guess I can break it into multiple like this as well :+1:

2022-10-12 11:53 UTC, mutantcornholio commented on rust-features.sh
> +main "$@"; exit
what's the purpose of `exit` here?

2022-10-12 11:54 UTC, ggwpez commented on rust-features.sh
> +main "$@"; exit
I just removed it, should be not needed.

2022-10-12 11:55 UTC, mutantcornholio approved these changes
anyway, much more readable and maintainable now, thank you!

2022-10-12 12:37 UTC, merged